
service: my-first-service
# app and org for use with dashboard.serverless.com
app: my-first-app
org: hamza3256


provider:
  name: aws
  runtime: nodejs10.x

outputs:
  custom-output: any-value-here


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
